apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress-operator
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ingress-operator
    namespace: default
roleRef:
  kind: Role
  name: ingress-operator
  apiGroup: rbac.authorization.k8s.io
