apiVersion: v1
kind: Service
metadata:
  name: echo-svc
  namespace: default
  annotations:
    auto-ingress: "/"
spec:
  selector:
    app: echo
  ports:
    - name: http
      port: 80
      targetPort: 80
